permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: Peter Zhu
  email: pigstars@icloud.com
  link: 
  weibo: 
  github: https://github.com/pigstars
  zhihu: 

# 站点信息
title: Peter's Blog
description: My personal note-blog.
url: http://www.pigsatrs.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/gavatar.jpg
favicon: /public/img/favicon.ico

# google analytics 设置

# disqus 设置
disqus:
  shortname: gotoshare

# 主题设置，自动激活某个标签
active: 思考

# 首页除了最新文章外显示分类
cates: 


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

plugins: [jekyll-paginate]

gems:
  - jekyll-sitemap
  
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]